# Copyright 2026 Open Source Robotics Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import csv
from http.server import BaseHTTPRequestHandler
from http.server import HTTPServer
import json
import os
import sys
import threading
import webbrowser


HTML_TEMPLATE = '\n'.join([
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    '    <meta charset="UTF-8">',
    '    <meta name="viewport" content="width=device-width, initial-scale=1.0">',
    '    <title>RMF Trajectory Visualizer</title>',
    '    <link rel="preconnect" href="https://fonts.googleapis.com">',
    '    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>',
    (
        '    <link href="https://fonts.googleapis.com/css2?'
        'family=Outfit:wght@300;400;500;600;700&'
        'family=JetBrains+Mono:wght@400;500;600&display=swap" '
        'rel="stylesheet">'
    ),
    '    <style>',
    '        :root {',
    '            --bg-main: #09090b;',
    '            --bg-sidebar: #18181b;',
    '            --bg-card: #27272a;',
    '            --border-color: #3f3f46;',
    '            --text-primary: #f4f4f5;',
    '            --text-secondary: #a1a1aa;',
    '            --accent: #2563eb;',
    '            --accent-hover: #1d4ed8;',
    '            --accent-glow: rgba(37, 99, 235, 0.4);',
    '        }',
    '',
    '        * {',
    '            box-sizing: border-box;',
    '            margin: 0;',
    '            padding: 0;',
    '        }',
    '',
    '        body {',
    '            font-family: "Outfit", -apple-system, BlinkMacSystemFont,',
    '                "Segoe UI", Roboto, sans-serif;',
    '            background-color: var(--bg-main);',
    '            color: var(--text-primary);',
    '            overflow: hidden;',
    '            height: 100vh;',
    '        }',
    '',
    '        .app-container {',
    '            display: flex;',
    '            width: 100vw;',
    '            height: 100vh;',
    '        }',
    '',
    '        /* Sidebar Styling */',
    '        .sidebar {',
    '            width: 350px;',
    '            background-color: var(--bg-sidebar);',
    '            border-right: 1px solid var(--border-color);',
    '            padding: 24px;',
    '            display: flex;',
    '            flex-direction: column;',
    '            gap: 20px;',
    '            overflow-y: auto;',
    '            flex-shrink: 0;',
    '            box-shadow: 4px 0 24px rgba(0, 0, 0, 0.3);',
    '        }',
    '',
    '        .header h2 {',
    '            font-size: 22px;',
    '            font-weight: 700;',
    '            letter-spacing: -0.5px;',
    '            margin-bottom: 6px;',
    '            background: linear-gradient(',
    '                135deg,',
    '                #ffffff 0%,',
    '                #a1a1aa 100%',
    '            );',
    '            -webkit-background-clip: text;',
    '            -webkit-text-fill-color: transparent;',
    '        }',
    '',
    '        .file-name {',
    '            font-family: "JetBrains Mono", monospace;',
    '            font-size: 11px;',
    '            color: var(--text-secondary);',
    '            word-break: break-all;',
    '            background: rgba(39, 39, 42, 0.5);',
    '            padding: 4px 8px;',
    '            border-radius: 4px;',
    '            border: 1px solid rgba(63, 63, 70, 0.3);',
    '        }',
    '',
    '        .stats-panel {',
    '            display: grid;',
    '            grid-template-columns: 1fr 1fr;',
    '            gap: 12px;',
    '            background: rgba(39, 39, 42, 0.3);',
    '            border: 1px solid rgba(63, 63, 70, 0.4);',
    '            border-radius: 12px;',
    '            padding: 12px;',
    '        }',
    '',
    '        .stat-item {',
    '            display: flex;',
    '            flex-direction: column;',
    '            gap: 4px;',
    '        }',
    '',
    '        .stat-label {',
    '            font-size: 10px;',
    '            text-transform: uppercase;',
    '            letter-spacing: 0.5px;',
    '            color: var(--text-secondary);',
    '        }',
    '',
    '        .stat-value {',
    '            font-size: 16px;',
    '            font-weight: 600;',
    '            font-family: "JetBrains Mono", monospace;',
    '        }',
    '',
    '        .control-section, .robots-section {',
    '            display: flex;',
    '            flex-direction: column;',
    '            gap: 14px;',
    '        }',
    '',
    '        .control-section h3, .robots-section h3 {',
    '            font-size: 13px;',
    '            font-weight: 600;',
    '            text-transform: uppercase;',
    '            letter-spacing: 0.5px;',
    '            color: var(--text-secondary);',
    '            border-bottom: 1px solid rgba(63, 63, 70, 0.3);',
    '            padding-bottom: 6px;',
    '        }',
    '',
    '        .play-controls {',
    '            display: flex;',
    '            gap: 10px;',
    '        }',
    '',
    '        .btn {',
    '            display: flex;',
    '            align-items: center;',
    '            justify-content: center;',
    '            gap: 8px;',
    '            padding: 10px 16px;',
    '            border-radius: 8px;',
    '            font-size: 14px;',
    '            font-weight: 500;',
    '            cursor: pointer;',
    '            transition: all 0.15s ease;',
    '            border: 1px solid transparent;',
    '            outline: none;',
    '            user-select: none;',
    '        }',
    '',
    '        .btn-primary {',
    '            background-color: var(--accent);',
    '            color: #ffffff;',
    '            flex-grow: 1;',
    '            box-shadow: 0 4px 12px var(--accent-glow);',
    '        }',
    '',
    '        .btn-primary:hover {',
    '            background-color: var(--accent-hover);',
    '        }',
    '',
    '        .btn-secondary {',
    '            background-color: var(--bg-card);',
    '            color: var(--text-primary);',
    '            border-color: var(--border-color);',
    '        }',
    '',
    '        .btn-secondary:hover {',
    '            background-color: rgba(63, 63, 70, 0.8);',
    '            border-color: #52525b;',
    '        }',
    '',
    '        .icon {',
    '            width: 18px;',
    '            height: 18px;',
    '            fill: currentColor;',
    '        }',
    '',
    '        .control-group {',
    '            display: flex;',
    '            flex-direction: column;',
    '            gap: 6px;',
    '        }',
    '',
    '        .control-group label {',
    '            font-size: 13px;',
    '            color: var(--text-secondary);',
    '            display: flex;',
    '            justify-content: space-between;',
    '            align-items: center;',
    '        }',
    '',
    '        .select-input {',
    '            background-color: var(--bg-card);',
    '            color: var(--text-primary);',
    '            border: 1px solid var(--border-color);',
    '            padding: 8px 12px;',
    '            border-radius: 8px;',
    '            font-size: 13px;',
    '            outline: none;',
    '            font-family: inherit;',
    '            cursor: pointer;',
    '        }',
    '',
    '        .select-input:hover {',
    '            border-color: #52525b;',
    '        }',
    '',
    '        .slider {',
    '            -webkit-appearance: none;',
    '            width: 100%;',
    '            height: 6px;',
    '            border-radius: 3px;',
    '            background: var(--bg-card);',
    '            outline: none;',
    '            cursor: pointer;',
    '        }',
    '',
    '        .slider::-webkit-slider-thumb {',
    '            -webkit-appearance: none;',
    '            width: 16px;',
    '            height: 16px;',
    '            border-radius: 50%;',
    '            background: var(--accent);',
    '            cursor: pointer;',
    '            transition: transform 0.1s, background-color 0.15s;',
    '            box-shadow: 0 2px 6px rgba(0, 0, 0, 0.4);',
    '        }',
    '',
    '        .slider::-webkit-slider-thumb:hover {',
    '            transform: scale(1.2);',
    '            background-color: var(--accent-hover);',
    '        }',
    '',
    '        .checkbox-group {',
    '            flex-direction: row;',
    '            align-items: center;',
    '            gap: 8px;',
    '            cursor: pointer;',
    '            user-select: none;',
    '            font-size: 13px;',
    '            color: var(--text-primary);',
    '        }',
    '',
    '        .checkbox-group input {',
    '            cursor: pointer;',
    '            width: 16px;',
    '            height: 16px;',
    '            accent-color: var(--accent);',
    '        }',
    '',
    '        .mono-text {',
    '            font-family: "JetBrains Mono", monospace;',
    '            font-weight: 500;',
    '        }',
    '',
    '        .robot-list {',
    '            max-height: 280px;',
    '            overflow-y: auto;',
    '            display: flex;',
    '            flex-direction: column;',
    '            gap: 6px;',
    '            padding-right: 4px;',
    '        }',
    '',
    '        .robot-item {',
    '            display: flex;',
    '            align-items: center;',
    '            justify-content: space-between;',
    '            padding: 8px 12px;',
    '            background: rgba(39, 39, 42, 0.25);',
    '            border: 1px solid rgba(63, 63, 70, 0.3);',
    '            border-radius: 8px;',
    '            transition: all 0.15s ease;',
    '        }',
    '',
    '        .robot-item:hover {',
    '            background: rgba(39, 39, 42, 0.5);',
    '            border-color: rgba(63, 63, 70, 0.5);',
    '        }',
    '',
    '        .robot-info {',
    '            display: flex;',
    '            align-items: center;',
    '            gap: 8px;',
    '            cursor: pointer;',
    '            flex-grow: 1;',
    '            user-select: none;',
    '        }',
    '',
    '        .color-badge {',
    '            width: 12px;',
    '            height: 12px;',
    '            border-radius: 3px;',
    '            flex-shrink: 0;',
    '        }',
    '',
    '        .robot-name {',
    '            font-weight: 500;',
    '            color: var(--text-primary);',
    '            font-size: 13px;',
    '        }',
    '',
    '        .robot-actions {',
    '            display: flex;',
    '            gap: 6px;',
    '            align-items: center;',
    '        }',
    '',
    '        .action-btn {',
    '            background: transparent;',
    '            border: none;',
    '            cursor: pointer;',
    '            color: var(--text-secondary);',
    '            padding: 4px;',
    '            border-radius: 4px;',
    '            display: flex;',
    '            align-items: center;',
    '            justify-content: center;',
    '            transition: all 0.15s;',
    '        }',
    '',
    '        .action-btn:hover {',
    '            color: #ffffff;',
    '            background: rgba(63, 63, 70, 0.5);',
    '        }',
    '',
    '        .action-btn.active {',
    '            color: #3b82f6;',
    '            background: rgba(59, 130, 246, 0.15);',
    '        }',
    '',
    '        /* Main Content Panel */',
    '        .main-content {',
    '            flex-grow: 1;',
    '            position: relative;',
    '            height: 100%;',
    '            background-color: var(--bg-main);',
    '        }',
    '',
    '        .canvas-container {',
    '            width: 100%;',
    '            height: 100%;',
    '            position: relative;',
    '        }',
    '',
    '        canvas {',
    '            display: block;',
    '            width: 100%;',
    '            height: 100%;',
    '        }',
    '',
    '        /* Overlays */',
    '        .coords-display {',
    '            position: absolute;',
    '            bottom: 20px;',
    '            right: 20px;',
    '            background: rgba(24, 24, 27, 0.8);',
    '            border: 1px solid rgba(63, 63, 70, 0.5);',
    '            padding: 6px 12px;',
    '            border-radius: 6px;',
    '            font-family: "JetBrains Mono", monospace;',
    '            font-size: 12px;',
    '            color: var(--text-secondary);',
    '            backdrop-filter: blur(8px);',
    '            pointer-events: none;',
    '            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3);',
    '        }',
    '',
    '        .instructions {',
    '            background: rgba(9, 9, 11, 0.85);',
    '            border: 1px solid rgba(39, 39, 42, 0.6);',
    '            padding: 8px 16px;',
    '            border-radius: 8px;',
    '            font-size: 11px;',
    '            text-transform: uppercase;',
    '            letter-spacing: 0.5px;',
    '            color: var(--text-secondary);',
    '            backdrop-filter: blur(8px);',
    '            position: absolute;',
    '            bottom: 20px;',
    '            left: 50%;',
    '            transform: translateX(-50%);',
    '            pointer-events: none;',
    '            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3);',
    '        }',
    '',
    '        .tooltip {',
    '            position: fixed;',
    '            pointer-events: none;',
    '            background: rgba(24, 24, 27, 0.95);',
    '            border: 1px solid rgba(82, 82, 91, 0.8);',
    '            backdrop-filter: blur(8px);',
    '            border-radius: 8px;',
    '            padding: 12px;',
    '            color: #f4f4f5;',
    '            font-family: "Outfit", sans-serif;',
    '            font-size: 13px;',
    '            display: none;',
    '            box-shadow: 0 6px 24px rgba(0, 0, 0, 0.5);',
    '            z-index: 100;',
    '            min-width: 160px;',
    '        }',
    '',
    '        .tooltip h4 {',
    '            margin: 0 0 6px 0;',
    '            font-weight: 600;',
    '            font-size: 14px;',
    '            border-bottom: 1px solid rgba(255, 255, 255, 0.1);',
    '            padding-bottom: 6px;',
    '        }',
    '',
    '        .tooltip-row {',
    '            display: flex;',
    '            justify-content: space-between;',
    '            gap: 16px;',
    '            margin-bottom: 4px;',
    '        }',
    '',
    '        .tooltip-row:last-child {',
    '            margin-bottom: 0;',
    '        }',
    '',
    '        .tooltip .label {',
    '            color: var(--text-secondary);',
    '        }',
    '',
    '        .tooltip .val {',
    '            font-family: "JetBrains Mono", monospace;',
    '            font-weight: 500;',
    '        }',
    '',
    '        /* Scrollbars */',
    '        ::-webkit-scrollbar {',
    '            width: 6px;',
    '        }',
    '        ::-webkit-scrollbar-track {',
    '            background: transparent;',
    '        }',
    '        ::-webkit-scrollbar-thumb {',
    '            background: rgba(63, 63, 70, 0.5);',
    '            border-radius: 3px;',
    '        }',
    '        ::-webkit-scrollbar-thumb:hover {',
    '            background: rgba(82, 82, 91, 0.8);',
    '        }',
    '    </style>',
    '</head>',
    '<body>',
    '    <div class="app-container">',
    '        <!-- Sidebar -->',
    '        <aside class="sidebar">',
    '            <div class="header">',
    '                <h2>RMF Path Visualizer</h2>',
    '                <div class="file-name" id="fileName">trajectory.csv</div>',
    '            </div>',
    '            ',
    '            <div class="stats-panel">',
    '                <div class="stat-item">',
    '                    <span class="stat-label">Duration</span>',
    '                    <span class="stat-value" id="durationVal">0.0s</span>',
    '                </div>',
    '                <div class="stat-item">',
    '                    <span class="stat-label">Robots</span>',
    '                    <span class="stat-value" id="robotCountVal">0</span>',
    '                </div>',
    '            </div>',
    '',
    '            <div class="control-section">',
    '                <h3>Controls</h3>',
    '                <div class="play-controls">',
    '                    <button id="playBtn" class="btn btn-primary">',
    (
        '                        <svg id="playIcon" viewBox="0 0 24 24" '
        'class="icon"><path d="M8 5v14l11-7z"/></svg>'
    ),
    '                        <span id="playText">Play</span>',
    '                    </button>',
    '                    <button id="resetBtn" class="btn btn-secondary" title="Reset View">',
    (
        '                        <svg viewBox="0 0 24 24" class="icon">'
        '<path d="M12 5V1L7 6l5 5V7c3.31 0 6 2.69 6 6s-2.69 6-6 6-6-2.69'
        '-6-6H4c0 4.42 3.58 8 8 8s8-3.58 8-8-3.58-8-8-8z"/></svg>'
    ),
    '                    </button>',
    '                </div>',
    '                ',
    '                <div class="control-group">',
    '                    <label for="speedSelect">Speed</label>',
    '                    <select id="speedSelect" class="select-input">',
    '                        <option value="0.25">0.25x</option>',
    '                        <option value="0.5">0.5x</option>',
    '                        <option value="1" selected>1.0x</option>',
    '                        <option value="2">2.0x</option>',
    '                        <option value="5">5.0x</option>',
    '                        <option value="10">10.0x</option>',
    '                    </select>',
    '                </div>',
    '',
    '                <div class="control-group">',
    '                    <label>Time: <span id="timeVal" class="mono-text">0.00s</span></label>',
    (
        '                    <input type="range" id="timeSlider" '
        'class="slider" min="0" max="100" step="any" value="0">'
    ),
    '                </div>',
    '',
    '                <div class="control-group">',
    (
        '                    <label>Robot Radius: <span id="radiusVal" '
        'class="mono-text">0.30m</span></label>'
    ),
    (
        '                    <input type="range" id="radiusSlider" '
        'class="slider" min="0.05" max="2.0" step="0.05" value="0.30">'
    ),
    '                </div>',
    '                ',
    '                <div class="control-group checkbox-group">',
    '                    <label>',
    (
        '                        <input type="checkbox" '
        'id="showTrails" checked> Show Trajectory Trails'
    ),
    '                    </label>',
    '                </div>',
    '            </div>',
    '',
    '            <div class="robots-section">',
    '                <h3>Robots</h3>',
    '                <div id="robotList" class="robot-list">',
    '                    <!-- Dynamic robot list -->',
    '                </div>',
    '            </div>',
    '        </aside>',
    '',
    '        <!-- Canvas -->',
    '        <main class="main-content">',
    '            <div class="canvas-container">',
    '                <canvas id="vizCanvas"></canvas>',
    '                <div class="coords-display" id="coordsDisplay">X: 0.00, Y: 0.00</div>',
    (
        '                <div class="instructions">Drag to Pan • '
        'Scroll to Zoom • Double Click to Auto-Fit</div>'
    ),
    '            </div>',
    '        </main>',
    '    </div>',
    '',
    '    <!-- Tooltip -->',
    '    <div class="tooltip" id="tooltip"></div>',
    '',
    '    <script>',
    '        // Injected data',
    '        const trajectoryData = {{TRAJECTORY_DATA}};',
    '        const csvFileName = "{{CSV_FILE_NAME}}";',
    '    </script>',
    '    <script>',
    '        // Set filename in UI',
    '        document.getElementById("fileName").textContent = csvFileName;',
    '',
    '        // Palette of premium colors',
    '        const colors = [',
    '            "#3b82f6", // blue',
    '            "#10b981", // green',
    '            "#f59e0b", // amber',
    '            "#8b5cf6", // purple',
    '            "#ec4899", // pink',
    '            "#06b6d4", // cyan',
    '            "#f43f5e", // rose',
    '            "#14b8a6", // teal',
    '            "#eab308", // yellow',
    '            "#ef4444"  // red',
    '        ];',
    '',
    '        // Process trajectories',
    '        const robots = trajectoryData.robots;',
    '        const robotIds = Object.keys(robots);',
    '        ',
    '        let minT = trajectoryData.min_t;',
    '        let maxT = trajectoryData.max_t;',
    '        let currentTime = minT;',
    '        let playSpeed = 1.0;',
    '        let isPlaying = false;',
    '        let lastTime = 0;',
    '        let robotRadius = 0.30;',
    '        let showTrails = true;',
    '        let followRobotId = null;',
    '        let haloPulse = 0;',
    '',
    '        // Bounding box computation for auto-fit',
    '        let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;',
    '        ',
    '        robotIds.forEach((id, idx) => {',
    '            const robot = robots[id];',
    '            robot.color = colors[idx % colors.length];',
    '            robot.visible = true;',
    '            ',
    '            robot.points.forEach(pt => {',
    '                if (pt.x < minX) minX = pt.x;',
    '                if (pt.x > maxX) maxX = pt.x;',
    '                if (pt.y < minY) minY = pt.y;',
    '                if (pt.y > maxY) maxY = pt.y;',
    '            });',
    '        });',
    '',
    '        // Set duration and count in UI',
    '        const duration = maxT - minT;',
    '        document.getElementById("durationVal").textContent = duration.toFixed(1) + "s";',
    '        document.getElementById("robotCountVal").textContent = robotIds.length;',
    '',
    '        // Setup time slider bounds',
    '        const timeSlider = document.getElementById("timeSlider");',
    '        timeSlider.min = minT;',
    '        timeSlider.max = maxT;',
    '        timeSlider.value = minT;',
    '        document.getElementById("timeVal").textContent = currentTime.toFixed(2) + "s";',
    '',
    '        if (minT === maxT) {',
    '            timeSlider.disabled = true;',
    '            timeSlider.max = minT + 1;',
    '        }',
    '',
    '        // Canvas Setup',
    '        const canvas = document.getElementById("vizCanvas");',
    '        const ctx = canvas.getContext("2d");',
    '        let scale = 50.0;',
    '        let offsetX = 0;',
    '        let offsetY = 0;',
    '',
    '        // Coordinate transforms',
    '        function toScreenX(worldX) {',
    '            return worldX * scale + offsetX;',
    '        }',
    '        function toScreenY(worldY) {',
    '            return -worldY * scale + offsetY;',
    '        }',
    '        function toWorldX(screenX) {',
    '            return (screenX - offsetX) / scale;',
    '        }',
    '        function toWorldY(screenY) {',
    '            return -(screenY - offsetY) / scale;',
    '        }',
    '',
    '        // Auto-fit to bounds',
    '        function fitToScreen() {',
    (
        '            if (minX === Infinity || maxX === -Infinity || '
        'minY === Infinity || maxY === -Infinity) {'
    ),
    '                scale = 50;',
    '                offsetX = canvas.width / 2;',
    '                offsetY = canvas.height / 2;',
    '                return;',
    '            }',
    '',
    '            const margin = 80; // px margin around bounds',
    '            const dpr = window.devicePixelRatio || 1;',
    '            const wWidth = (canvas.width / dpr) - margin * 2;',
    '            const wHeight = (canvas.height / dpr) - margin * 2;',
    '',
    '            const worldW = maxX - minX;',
    '            const worldH = maxY - minY;',
    '',
    '            if (worldW === 0 && worldH === 0) {',
    '                scale = 50;',
    '            } else {',
    '                const scaleX = wWidth / (worldW || 1);',
    '                const scaleY = wHeight / (worldH || 1);',
    '                scale = Math.min(scaleX, scaleY);',
    '                // Clamp scale to sensible limits',
    '                scale = Math.max(1, Math.min(1000, scale));',
    '            }',
    '',
    '            const centerWorldX = (minX + maxX) / 2;',
    '            const centerWorldY = (minY + maxY) / 2;',
    '',
    '            offsetX = (canvas.width / dpr) / 2 - centerWorldX * scale;',
    '            offsetY = (canvas.height / dpr) / 2 + centerWorldY * scale;',
    '        }',
    '',
    '        // Setup Robot Sidebar list',
    '        const robotListContainer = document.getElementById("robotList");',
    '        robotIds.forEach(id => {',
    '            const robot = robots[id];',
    '            ',
    '            const item = document.createElement("div");',
    '            item.className = "robot-item";',
    '            ',
    '            const info = document.createElement("div");',
    '            info.className = "robot-info";',
    '            ',
    '            const badge = document.createElement("span");',
    '            badge.className = "color-badge";',
    '            badge.style.backgroundColor = robot.color;',
    '            ',
    '            const name = document.createElement("span");',
    '            name.className = "robot-name";',
    '            name.textContent = id;',
    '            ',
    '            info.appendChild(badge);',
    '            info.appendChild(name);',
    '            ',
    '            // Checkbox to show/hide',
    '            const checkbox = document.createElement("input");',
    '            checkbox.type = "checkbox";',
    '            checkbox.checked = true;',
    '            checkbox.style.marginRight = "8px";',
    '            checkbox.addEventListener("change", (e) => {',
    '                robot.visible = e.target.checked;',
    '                draw();',
    '            });',
    '            info.prepend(checkbox);',
    '',
    '            const actions = document.createElement("div");',
    '            actions.className = "robot-actions";',
    '            ',
    '            // Focus target button',
    '            const focusBtn = document.createElement("button");',
    '            focusBtn.className = "action-btn focus-btn";',
    '            focusBtn.title = "Focus Camera";',
    (
        '            focusBtn.innerHTML = `<svg viewBox="0 0 24 24" class="icon" '
        'style="width: 14px; height: 14px;"><path d="M12 8c-2.21 0-4 1.79-4 4s'
        '1.79 4 4 4 4-1.79 4-4-1.79-4-4-4zm-9 5h2c.55 0 1-.45 1-1s-.45-1-1-1H3'
        'c-.55 0-1 .45-1 1s.45 1 1 1zm18-2h-2c-.55 0-1 .45-1 1s.45 1 1 1h2c.55'
        ' 0 1-.45 1-1s-.45-1-1-1zm-8-9c.55 0 1-.45 1-1V3c0-.55-.45-1-1-1s-1 .45'
        '-1 1v2c0 .55.45 1 1 1zm0 16c-.55 0-1 .45-1 1v2c0 .55.45 1 1 1s1-.45 1'
        '-1v-2c0-.55-.45-1-1-1z"/></svg>`;'
    ),
    '            ',
    '            focusBtn.addEventListener("click", () => {',
    '                document.querySelectorAll(".focus-btn").forEach(btn => {',
    '                    if (btn !== focusBtn) btn.classList.remove("active");',
    '                });',
    '                ',
    '                if (followRobotId === id) {',
    '                    followRobotId = null;',
    '                    focusBtn.classList.remove("active");',
    '                } else {',
    '                    followRobotId = id;',
    '                    focusBtn.classList.add("active");',
    '                    centerOnRobot(id);',
    '                    draw();',
    '                }',
    '            });',
    '            ',
    '            actions.appendChild(focusBtn);',
    '            item.appendChild(info);',
    '            item.appendChild(actions);',
    '            robotListContainer.appendChild(item);',
    '        });',
    '',
    '        // Compute interpolated position',
    '        function getRobotPositionAt(robot, t) {',
    '            const pts = robot.points;',
    '            if (pts.length === 0) return null;',
    (
        '            if (t <= pts[0].t) return { x: pts[0].x, y: pts[0].y, '
        'active: false };'
    ),
    (
        '            if (t >= pts[pts.length - 1].t) return { x: pts[pts.length'
        ' - 1].x, y: pts[pts.length - 1].y, active: false };'
    ),
    '            ',
    '            for (let i = 0; i < pts.length - 1; i++) {',
    '                const p1 = pts[i];',
    '                const p2 = pts[i+1];',
    '                if (t >= p1.t && t <= p2.t) {',
    '                    const dt = p2.t - p1.t;',
    (
        '                    if (dt === 0) return { x: p1.x, y: p1.y, '
        'active: true };'
    ),
    '                    const factor = (t - p1.t) / dt;',
    '                    return {',
    '                        x: p1.x + (p2.x - p1.x) * factor,',
    '                        y: p1.y + (p2.y - p1.y) * factor,',
    '                        active: true',
    '                    };',
    '                }',
    '            }',
    '            return null;',
    '        }',
    '',
    '        // Compute approximate heading',
    '        function getRobotHeadingAt(robot, t) {',
    '            const pts = robot.points;',
    '            if (pts.length < 2) return 0;',
    '            ',
    '            for (let i = 0; i < pts.length - 1; i++) {',
    '                const p1 = pts[i];',
    '                const p2 = pts[i+1];',
    '                if (t >= p1.t && t <= p2.t) {',
    '                    const dx = p2.x - p1.x;',
    '                    const dy = p2.y - p1.y;',
    '                    if (dx === 0 && dy === 0) continue;',
    '                    return Math.atan2(dy, dx);',
    '                }',
    '            }',
    '            // fallback to last known heading or look forward',
    '            return 0;',
    '        }',
    '',
    '        // Draw helper',
    '        function hexToRgba(hex, alpha) {',
    '            hex = hex.replace("#", "");',
    '            const r = parseInt(hex.substring(0, 2), 16);',
    '            const g = parseInt(hex.substring(2, 4), 16);',
    '            const b = parseInt(hex.substring(4, 6), 16);',
    '            return `rgba(${r}, ${g}, ${b}, ${alpha})`;',
    '        }',
    '',
    '        // Drawing Grid and Origin axes',
    '        function drawGrid() {',
    '            const idealSpacingPx = 60;',
    '            const idealWorldSpacing = idealSpacingPx / scale;',
    '            const log10 = Math.log10(idealWorldSpacing);',
    '            const powerOf10 = Math.pow(10, Math.floor(log10));',
    '            const ratio = idealWorldSpacing / powerOf10;',
    '            ',
    '            let gridSpacingWorld;',
    '            if (ratio < 1.5) gridSpacingWorld = powerOf10;',
    '            else if (ratio < 3.5) gridSpacingWorld = 2 * powerOf10;',
    '            else if (ratio < 7.5) gridSpacingWorld = 5 * powerOf10;',
    '            else gridSpacingWorld = 10 * powerOf10;',
    '',
    (
        '            const minGridX = Math.floor(toWorldX(0) / '
        'gridSpacingWorld) * gridSpacingWorld;'
    ),
    (
        '            const maxGridX = Math.ceil(toWorldX(canvas.width) / '
        'gridSpacingWorld) * gridSpacingWorld;'
    ),
    (
        '            const minGridY = Math.floor(toWorldY(canvas.height) / '
        'gridSpacingWorld) * gridSpacingWorld;'
    ),
    (
        '            const maxGridY = Math.ceil(toWorldY(0) / '
        'gridSpacingWorld) * gridSpacingWorld;'
    ),
    '',
    '            // Grid lines',
    '            ctx.strokeStyle = "#18181b";',
    '            ctx.lineWidth = 1;',
    '            ctx.fillStyle = "#71717a";',
    '            ctx.font = \'10px "JetBrains Mono"\';',
    '            ctx.textAlign = "center";',
    '            ctx.textBaseline = "top";',
    '',
    '            for (let x = minGridX; x <= maxGridX; x += gridSpacingWorld) {',
    '                const sx = toScreenX(x);',
    '                ctx.beginPath();',
    '                ctx.moveTo(sx, 0);',
    '                ctx.lineTo(sx, canvas.height);',
    '                ctx.stroke();',
    '                // Draw label at screen bottom margin',
    '                ctx.fillText(x.toFixed(1), sx, canvas.height - 20);',
    '            }',
    '',
    '            ctx.textAlign = "right";',
    '            ctx.textBaseline = "middle";',
    '            for (let y = minGridY; y <= maxGridY; y += gridSpacingWorld) {',
    '                const sy = toScreenY(y);',
    '                ctx.beginPath();',
    '                ctx.moveTo(0, sy);',
    '                ctx.lineTo(canvas.width, sy);',
    '                ctx.stroke();',
    '                // Draw label at left margin',
    '                ctx.fillText(y.toFixed(1), 35, sy);',
    '            }',
    '',
    '            // Origin Axes',
    '            ctx.strokeStyle = "#27272a";',
    '            ctx.lineWidth = 1.5;',
    '            if (toWorldX(0) <= 0 && toWorldX(canvas.width) >= 0) {',
    '                const sx = toScreenX(0);',
    '                ctx.beginPath();',
    '                ctx.moveTo(sx, 0);',
    '                ctx.lineTo(sx, canvas.height);',
    '                ctx.stroke();',
    '            }',
    '            if (toWorldY(canvas.height) <= 0 && toWorldY(0) >= 0) {',
    '                const sy = toScreenY(0);',
    '                ctx.beginPath();',
    '                ctx.moveTo(0, sy);',
    '                ctx.lineTo(canvas.width, sy);',
    '                ctx.stroke();',
    '            }',
    '        }',
    '',
    '        // Draw Trails',
    '        function drawTrails() {',
    '            for (const id of robotIds) {',
    '                const robot = robots[id];',
    '                if (!robot.visible || robot.points.length === 0) continue;',
    '',
    '                // Faint planned trajectory',
    '                ctx.beginPath();',
    '                ctx.strokeStyle = hexToRgba(robot.color, 0.15);',
    '                ctx.lineWidth = 1.5;',
    '                ctx.setLineDash([4, 4]);',
    '                robot.points.forEach((pt, idx) => {',
    '                    const sx = toScreenX(pt.x);',
    '                    const sy = toScreenY(pt.y);',
    '                    if (idx === 0) ctx.moveTo(sx, sy);',
    '                    else ctx.lineTo(sx, sy);',
    '                });',
    '                ctx.stroke();',
    '                ctx.setLineDash([]);',
    '',
    '                // Path already traveled',
    '                ctx.beginPath();',
    '                ctx.strokeStyle = robot.color;',
    '                ctx.lineWidth = 2.5;',
    '                let started = false;',
    '                for (const pt of robot.points) {',
    '                    if (pt.t > currentTime) break;',
    '                    const sx = toScreenX(pt.x);',
    '                    const sy = toScreenY(pt.y);',
    '                    if (!started) {',
    '                        ctx.moveTo(sx, sy);',
    '                        started = true;',
    '                    } else {',
    '                        ctx.lineTo(sx, sy);',
    '                    }',
    '                }',
    '                if (started) {',
    '                    ctx.stroke();',
    '                }',
    '            }',
    '        }',
    '',
    '        // Draw Robots',
    '        function drawRobots() {',
    '            for (const id of robotIds) {',
    '                const robot = robots[id];',
    '                if (!robot.visible) continue;',
    '',
    '                const pos = getRobotPositionAt(robot, currentTime);',
    '                if (!pos) continue;',
    '',
    '                const sx = toScreenX(pos.x);',
    '                const sy = toScreenY(pos.y);',
    '                const rPx = robotRadius * scale;',
    '',
    '                // Draw pulsing focus halo',
    '                if (followRobotId === id) {',
    '                    const pulseRadius = rPx + 4 + Math.sin(haloPulse) * 4;',
    '                    ctx.beginPath();',
    '                    ctx.arc(sx, sy, pulseRadius, 0, Math.PI * 2);',
    '                    ctx.strokeStyle = hexToRgba(robot.color, 0.4);',
    '                    ctx.lineWidth = 2;',
    '                    ctx.stroke();',
    '                }',
    '',
    '                // Draw footprint',
    '                ctx.beginPath();',
    '                ctx.arc(sx, sy, rPx, 0, Math.PI * 2);',
    (
        '                ctx.fillStyle = pos.active ? '
        'hexToRgba(robot.color, 0.2) : "rgba(100, 100, 100, 0.1)";'
    ),
    '                ctx.fill();',
    '                ctx.strokeStyle = pos.active ? robot.color : "#71717a";',
    '                ctx.lineWidth = 2;',
    '                ctx.stroke();',
    '',
    '                // Draw heading',
    '                const heading = getRobotHeadingAt(robot, currentTime);',
    '                ctx.beginPath();',
    '                ctx.moveTo(sx, sy);',
    (
        '                ctx.lineTo(sx + Math.cos(heading) * rPx, '
        'sy - Math.sin(heading) * rPx);'
    ),
    '                ctx.strokeStyle = pos.active ? "#ffffff" : "#71717a";',
    '                ctx.lineWidth = 2;',
    '                ctx.stroke();',
    '',
    '                // Center dot',
    '                ctx.beginPath();',
    '                ctx.arc(sx, sy, 3.5, 0, Math.PI * 2);',
    '                ctx.fillStyle = pos.active ? "#ffffff" : "#71717a";',
    '                ctx.fill();',
    '',
    '                // Label',
    '                ctx.fillStyle = "#ffffff";',
    '                ctx.font = \'bold 11px "Outfit"\';',
    '                ctx.textAlign = "center";',
    '                ctx.textBaseline = "bottom";',
    '                ctx.fillText(id, sx, sy - rPx - 6);',
    '            }',
    '        }',
    '',
    '        // Draw Canvas Loop',
    '        function draw() {',
    '            ctx.clearRect(0, 0, canvas.width, canvas.height);',
    '            drawGrid();',
    '            if (showTrails) {',
    '                drawTrails();',
    '            }',
    '            drawRobots();',
    '        }',
    '',
    '        // Center on a robot',
    '        function centerOnRobot(robotId) {',
    '            const robot = robots[robotId];',
    '            if (!robot) return;',
    '            const pos = getRobotPositionAt(robot, currentTime);',
    '            if (!pos) return;',
    '',
    '            const dpr = window.devicePixelRatio || 1;',
    '            offsetX = (canvas.width / dpr) / 2 - pos.x * scale;',
    '            offsetY = (canvas.height / dpr) / 2 + pos.y * scale;',
    '        }',
    '',
    '        // Animation loop',
    '        function animate(now) {',
    '            if (!isPlaying) return;',
    '',
    '            if (lastTime === 0) lastTime = now;',
    '            const elapsed = (now - lastTime) / 1000;',
    '            lastTime = now;',
    '',
    '            currentTime += elapsed * playSpeed;',
    '            if (currentTime > maxT) {',
    '                currentTime = minT;',
    '            }',
    '',
    '            // Update range inputs',
    '            timeSlider.value = currentTime;',
    (
        '            document.getElementById("timeVal").textContent = '
        'currentTime.toFixed(2) + "s";'
    ),
    '',
    '            if (followRobotId) {',
    '                centerOnRobot(followRobotId);',
    '            }',
    '',
    '            haloPulse = (haloPulse + 0.08) % (Math.PI * 2);',
    '',
    '            draw();',
    '            requestAnimationFrame(animate);',
    '        }',
    '',
    '        // Resize handler',
    '        function resizeCanvas() {',
    '            const rect = canvas.getBoundingClientRect();',
    '            const dpr = window.devicePixelRatio || 1;',
    '            canvas.width = rect.width * dpr;',
    '            canvas.height = rect.height * dpr;',
    '            ctx.scale(dpr, dpr);',
    '            draw();',
    '        }',
    '',
    '        window.addEventListener("resize", resizeCanvas);',
    '',
    '        // Interaction state',
    '        let isDragging = false;',
    '        let dragStart = { x: 0, y: 0 };',
    '        let hoverRobotId = null;',
    '        let mouseWorldX = 0;',
    '        let mouseWorldY = 0;',
    '',
    '        // Mouse pan and zoom handlers',
    '        canvas.addEventListener("mousedown", (e) => {',
    '            if (e.button === 0) { // left button',
    '                isDragging = true;',
    '                const dpr = window.devicePixelRatio || 1;',
    '                dragStart.x = e.clientX - offsetX;',
    '                dragStart.y = e.clientY - offsetY;',
    '',
    '                // Stop follow if manual pan occurs',
    '                if (followRobotId) {',
    '                    followRobotId = null;',
    (
        '                    document.querySelectorAll(".focus-btn").'
        'forEach(btn => btn.classList.remove("active"));'
    ),
    '                }',
    '            }',
    '        });',
    '',
    '        canvas.addEventListener("mousemove", (e) => {',
    '            const rect = canvas.getBoundingClientRect();',
    '            const sx = e.clientX - rect.left;',
    '            const sy = e.clientY - rect.top;',
    '',
    '            mouseWorldX = toWorldX(sx);',
    '            mouseWorldY = toWorldY(sy);',
    '',
    '            // Update coords display',
    (
        '            document.getElementById("coordsDisplay").textContent = '
        '`X: ${mouseWorldX.toFixed(2)}, Y: ${mouseWorldY.toFixed(2)}`;'
    ),
    '',
    '            if (isDragging) {',
    '                offsetX = e.clientX - dragStart.x;',
    '                offsetY = e.clientY - dragStart.y;',
    '                draw();',
    '            } else {',
    '                // Check robot hover for tooltips',
    '                let found = null;',
    '                let minDist = Infinity;',
    '                for (const id of robotIds) {',
    '                    const robot = robots[id];',
    '                    if (!robot.visible) continue;',
    '                    const pos = getRobotPositionAt(robot, currentTime);',
    '                    if (!pos) continue;',
    '',
    (
        '                    const dist = Math.sqrt((mouseWorldX - pos.x)**2 + '
        '(mouseWorldY - pos.y)**2);'
    ),
    '                    if (dist <= robotRadius && dist < minDist) {',
    '                        found = id;',
    '                        minDist = dist;',
    '                    }',
    '                }',
    '                hoverRobotId = found;',
    '                updateTooltip(e.clientX, e.clientY);',
    '            }',
    '        });',
    '',
    '        window.addEventListener("mouseup", () => {',
    '            isDragging = false;',
    '        });',
    '',
    '        canvas.addEventListener("wheel", (e) => {',
    '            e.preventDefault();',
    '            const rect = canvas.getBoundingClientRect();',
    '            const sx = e.clientX - rect.left;',
    '            const sy = e.clientY - rect.top;',
    '',
    '            const wx = toWorldX(sx);',
    '            const wy = toWorldY(sy);',
    '',
    '            const zoomFactor = e.deltaY < 0 ? 1.15 : 1 / 1.15;',
    '            scale = Math.max(2, Math.min(2000, scale * zoomFactor));',
    '',
    '            offsetX = sx - wx * scale;',
    '            offsetY = sy + wy * scale;',
    '            draw();',
    '        }, { passive: false });',
    '',
    '        canvas.addEventListener("dblclick", () => {',
    '            fitToScreen();',
    '            draw();',
    '        });',
    '',
    '        // Tooltip updates',
    '        const tooltip = document.getElementById("tooltip");',
    '        function updateTooltip(clientX, clientY) {',
    '            if (!hoverRobotId) {',
    '                tooltip.style.display = "none";',
    '                return;',
    '            }',
    '',
    '            const robot = robots[hoverRobotId];',
    '            const pos = getRobotPositionAt(robot, currentTime);',
    '            if (!pos) {',
    '                tooltip.style.display = "none";',
    '                return;',
    '            }',
    '',
    '            // Calculate current speed',
    '            let speed = 0;',
    '            const pts = robot.points;',
    '            for (let i = 0; i < pts.length - 1; i++) {',
    '                const p1 = pts[i];',
    '                const p2 = pts[i+1];',
    '                if (currentTime >= p1.t && currentTime <= p2.t) {',
    '                    const dt = p2.t - p1.t;',
    '                    if (dt > 0) {',
    (
        '                        const dist = Math.sqrt((p2.x - p1.x)**2 + '
        '(p2.y - p1.y)**2);'
    ),
    '                        speed = dist / dt;',
    '                    }',
    '                    break;',
    '                }',
    '            }',
    '',
    '            tooltip.style.borderColor = robot.color;',
    '            tooltip.innerHTML = `',
    '                <h4 style="color: ${robot.color}">${hoverRobotId}</h4>',
    '                <div class="tooltip-row">',
    '                    <span class="label">X:</span>',
    '                    <span class="val">${pos.x.toFixed(3)}m</span>',
    '                </div>',
    '                <div class="tooltip-row">',
    '                    <span class="label">Y:</span>',
    '                    <span class="val">${pos.y.toFixed(3)}m</span>',
    '                </div>',
    '                <div class="tooltip-row">',
    '                    <span class="label">Speed:</span>',
    '                    <span class="val">${speed.toFixed(2)} m/s</span>',
    '                </div>',
    '                <div class="tooltip-row">',
    '                    <span class="label">Status:</span>',
    (
        '                    <span class="val" style="color: ${pos.active ? '
        '"#10b981" : "#71717a"}">${pos.active ? "Active" : '
        '"Finished"}</span>'
    ),
    '                </div>',
    '            `;',
    '',
    '            tooltip.style.left = (clientX + 16) + "px";',
    '            tooltip.style.top = (clientY + 16) + "px";',
    '            tooltip.style.display = "block";',
    '        }',
    '',
    '        // Controls event binding',
    '        const playBtn = document.getElementById("playBtn");',
    '        const playText = document.getElementById("playText");',
    '        const playIcon = document.getElementById("playIcon");',
    '',
    '        playBtn.addEventListener("click", () => {',
    '            isPlaying = !isPlaying;',
    '            if (isPlaying) {',
    '                playText.textContent = "Pause";',
    (
        '                playIcon.innerHTML = \'<path d="M6 19h4V5H6v14zm8-14v'
        '14h4V5h-4z"/>\';'
    ),
    '                playBtn.classList.remove("btn-primary");',
    '                playBtn.classList.add("btn-secondary");',
    '                lastTime = 0;',
    '                animate(performance.now());',
    '            } else {',
    '                playText.textContent = "Play";',
    '                playIcon.innerHTML = \'<path d="M8 5v14l11-7z"/>\';',
    '                playBtn.classList.remove("btn-secondary");',
    '                playBtn.classList.add("btn-primary");',
    '            }',
    '        });',
    '',
    '        document.getElementById("resetBtn").addEventListener("click", () => {',
    '            currentTime = minT;',
    '            timeSlider.value = minT;',
    (
        '            document.getElementById("timeVal").textContent = '
        'currentTime.toFixed(2) + "s";'
    ),
    '            if (followRobotId) {',
    '                centerOnRobot(followRobotId);',
    '            }',
    '            draw();',
    '        });',
    '',
    '        document.getElementById("speedSelect").addEventListener("change", (e) => {',
    '            playSpeed = parseFloat(e.target.value);',
    '        });',
    '',
    '        document.getElementById("showTrails").addEventListener("change", (e) => {',
    '            showTrails = e.target.checked;',
    '            draw();',
    '        });',
    '',
    '        const radiusSlider = document.getElementById("radiusSlider");',
    '        radiusSlider.addEventListener("input", (e) => {',
    '            robotRadius = parseFloat(e.target.value);',
    (
        '            document.getElementById("radiusVal").textContent = '
        'robotRadius.toFixed(2) + "m";'
    ),
    '            draw();',
    '        });',
    '',
    '        // Initialize view',
    '        resizeCanvas();',
    '        fitToScreen();',
    '        draw();',
    '    </script>',
    '</body>',
    '</html>',
])


def parse_csv(file_path):
    robots = {}
    min_t = float('inf')
    max_t = float('-inf')

    with open(file_path, mode='r') as f:
        reader = csv.reader(f)
        try:
            _ = next(reader)
        except StopIteration:
            return None

        for row in reader:
            if not row or len(row) < 4:
                continue
            try:
                t = float(row[0])
                robot_id = row[1].strip()
                x = float(row[2])
                y = float(row[3])

                if not robot_id:
                    continue

                if robot_id not in robots:
                    robots[robot_id] = {
                        'points': []
                    }
                robots[robot_id]['points'].append(
                    {'t': t, 'x': x, 'y': y}
                )

                if t < min_t:
                    min_t = t
                if t > max_t:
                    max_t = t
            except ValueError:
                continue

    for robot_id in robots:
        robots[robot_id]['points'].sort(key=lambda pt: pt['t'])

    return {
        'min_t': min_t if min_t != float('inf') else 0.0,
        'max_t': max_t if max_t != float('-inf') else 0.0,
        'robots': robots
    }


class TrajectoryServer(BaseHTTPRequestHandler):
    html_content = ''

    def do_GET(self):
        if self.path == '/':
            self.send_response(200)
            self.send_header('Content-type', 'text/html')
            self.end_headers()
            self.wfile.write(self.html_content.encode('utf-8'))
        else:
            self.send_response(404)
            self.end_headers()
            self.wfile.write(b'Not Found')

    def log_message(self, format_str, *args):
        # Silence default logger output to keep terminal clean
        pass


def main():
    parser = argparse.ArgumentParser(
        description='Visualize robot trajectories from a simulation CSV file.'
    )
    parser.add_argument('csv_file', help='Path to the trajectory CSV file.')
    parser.add_argument(
        '--port', type=int, default=9567,
        help='Port to run the visualization server on (default: 9567).'
    )
    parser.add_argument(
        '--open', action='store_true',
        help='Open the visualizer in the default web browser.'
    )

    args = parser.parse_args()

    csv_path = os.path.abspath(args.csv_file)
    if not os.path.exists(csv_path):
        print(f"Error: File '{csv_path}' does not exist.", file=sys.stderr)
        sys.exit(1)

    print(f"Parsing '{csv_path}'...")
    data = parse_csv(csv_path)
    if not data or not data['robots']:
        print(
            f'Error: Could not parse any valid robot trajectory points from '
            f"'{csv_path}'. Check if format matches columns: t,robot_id,x,y.",
            file=sys.stderr
        )
        sys.exit(1)

    print(
        f"Loaded {len(data['robots'])} robots over timeline range: "
        f"[{data['min_t']:.2f}s, {data['max_t']:.2f}s]."
    )

    json_data = json.dumps(data)
    csv_file_name = os.path.basename(csv_path)
    html_content = HTML_TEMPLATE.replace('{{TRAJECTORY_DATA}}', json_data)
    html_content = html_content.replace('{{CSV_FILE_NAME}}', csv_file_name)

    TrajectoryServer.html_content = html_content

    try:
        server = HTTPServer(('0.0.0.0', args.port), TrajectoryServer)
    except OSError as e:
        print(f'Error starting server on port {args.port}: {e}', file=sys.stderr)
        print('Try running on a different port using: --port <number>', file=sys.stderr)
        sys.exit(1)

    url = f'http://localhost:{args.port}/'
    print('\n' + '=' * 70)
    print('Trajectory Visualizer server is running at:')
    print(f'  {url}')
    print('=' * 70)
    print(
        '\nIf you are accessing this remotely via SSH, you can forward this '
        'port to your local machine:'
    )
    print(f'  ssh -L {args.port}:localhost:{args.port} <user>@<remote_ip>')
    print('\nPress Ctrl+C to terminate the server.\n')

    if args.open:
        def open_browser():
            webbrowser.open(url)
        threading.Thread(target=open_browser, daemon=True).start()

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print('\nShutting down server...')
        server.server_close()
        print('Done.')


if __name__ == '__main__':
    main()
