FROM ros:jazzy-ros-base

# Disable interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Install core build dependencies, Rust prerequisites, and ROS 2 build tools
RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
        curl \
        git \
        python3-pip \
        python3-vcstool \
        clang \
        libclang-dev \
        build-essential \
        python3-colcon-common-extensions \
        python3-colcon-cargo\
        libssl-dev \
        pkg-config \
        && rm -rf /var/lib/apt/lists/*

# Install colcon extensions for Rust
RUN pip3 install --no-cache-dir --break-system-packages colcon-ros-cargo

# Install Rust toolchain (Stable) and global Cargo tools accessible to all users
ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:$PATH
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path && \
    cargo install cargo-ament-build && \
    chmod -R a+rwX /usr/local/cargo /usr/local/rustup


# Initialize Underlay Workspace
WORKDIR /opt/ros2_rust_ws

# Stage the prototype branch to resolve its rosdep system dependencies directly into the base image
COPY . /tmp/next_gen_prototype

# Install ROS 2 dependencies via rosdep for both underlay and prototype branch
RUN apt-get update && \
    rosdep init || true && \
    rosdep update && \
    rosdep install --from-paths /tmp/next_gen_prototype --ignore-src -yr --skip-keys="rclrs ament_cargo ament_python" && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /tmp/next_gen_prototype

# Build the Underlay Workspace
#RUN /bin/bash -c "source /opt/ros/jazzy/setup.bash && \
#    colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release"

# Provide automatic sourcing entrypoint configuration inside ~/.bashrc
RUN echo "source /opt/ros/jazzy/setup.bash" >> /root/.bashrc
#echo "source /opt/ros2_rust_ws/install/setup.bash" >> /root/.bashrc

CMD ["/bin/bash"]
