ARG ROS_DISTRO=jazzy

# ==========================================
# Builder
# ==========================================
FROM ghcr.io/open-rmf/ros2_rust_base:${ROS_DISTRO}

ENV DEBIAN_FRONTEND=noninteractive
ENV ROS_DISTRO=${ROS_DISTRO}

WORKDIR /nav2_traffic_ws/src

# Copy your workspace packages
COPY ./ ./next_gen_prototype

# Install package dependencies
WORKDIR /nav2_traffic_ws

RUN apt-get update && \
    rosdep update && \
    rosdep install \
        --from-paths src \
        --ignore-src -yr --skip-keys="rclrs ament_cargo ament_python" \
        --ignore-src \
        -r \
        -y && \
    rm -rf /var/lib/apt/lists/*

# Build the workspace
RUN . /opt/ros/${ROS_DISTRO}/setup.sh && \
    colcon build --packages-up-to sp_demo_nav2_bringup rmf_nav2_traffic rmf_path_server_demo rmf_path_server_test --symlink-install

# Source the workspace whenever a shell starts
RUN echo "source /nav2_traffic_ws/install/setup.bash" >> /root/.bashrc

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]
