grid_size: 0.5

safe_sets:
  - name: main_floor
    region:
      hint: axis_aligned_rectangle
      points: [0.0, 0.0, 20.0, 20.0]

parking_spots:
  - name: parking_a
    x: 1.0
    y: 1.0
    region:
      hint: axis_aligned_rectangle
      points: [0.5, 0.5, 1.5, 1.5]
  - name: parking_b
    x: 18.0
    y: 18.0
    region:
      hint: axis_aligned_rectangle
      points: [17.5, 17.5, 18.5, 18.5]
