name: Pixi CI

on:
  push:
    branches: [ epic/next-gen-base ]
  pull_request:
    branches: [ epic/next-gen-base ]

jobs:
  pixi-check:
    name: Pixi Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Prototype Repository
        uses: actions/checkout@v4

      - name: Set up Pixi Environment
        uses: prefix-dev/setup-pixi@v0.9.6
        with:
          run-install: true
          cache-key: pixi-env-cache

      - name: Dump Pixi Env
        run: |
          pixi run env
        shell: bash

      - name: Run Pixi Test Suite
        run: |
          pixi run test
        shell: bash

